authentication/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "authentication"

urlpatterns = [
    path('signup/', views.SignUpFormView.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='authentication/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.update_profile, name='update_profile'),
    path('profile/<str:username>/', views.ProfileDetailView.as_view(), name='profile'),
]

chatproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('main.urls')),
    path('', include('authentication.urls')),
    path('chats/', include('rooms.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    path('', views.get_frontpage, name='frontpage'),
]

rooms/urls.py
from django.urls import path

from . import views

app_name = "chats"

urlpatterns = [
    path('private/', views.list_private_chats, name='private_chats'),
    path('private/<str:username>/', views.get_private_chat, name='private_chat'),
    path('<slug:slug>/', views.get_room, name='room'),
    path('', views.list_rooms, name='rooms'),
]

rooms/models.py
from django.contrib.auth.models import User
from django.db import models


class Room(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=25, unique=True)
    private_chat = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Message(models.Model):
    room = models.ForeignKey(Room, related_name='messages', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='messages', null=True, on_delete=models.SET_NULL)
    content = models.TextField(max_length=100000)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_added',)

rooms/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User

from chatproject.settings import DEBUG
from .models import Room, Message
from .utils import split_dates

default_pfp = 'images/default_avatar.jpg'

NUMBER_OF_MESSAGES = 25

PROTOCOL = 'ws' if DEBUG else 'wss'

@login_required
def list_rooms(request):
    qs = Room.objects.filter(private_chat=False)
    rooms = []
    for room in qs:
        message = Message.objects.filter(room=room).first()
        rooms += [{'room': room, 'message': message}]
    return render(request, 'rooms/rooms.html', {'chats': rooms, 'dpfp': default_pfp})


@login_required
def get_room(request, slug):
    room = get_object_or_404(Room, slug=slug, private_chat=False)
    messages = room.messages.all()[0:NUMBER_OF_MESSAGES:-1]
    if messages:
        split_dates(messages)
    return render(request, 'rooms/room.html', {'room': room, 'messages': messages, 'dpfp': default_pfp, 'protocol': PROTOCOL})


@login_required
def list_private_chats(request):
    qs = Room.objects.filter(private_chat=True, slug__contains=request.user.username)
    chats = []
    for room in qs:
        username = room.slug.replace(request.user.username, '')
        receiver = User.objects.get(username=username)
        message = room.messages.all().first()
        chats += [{'receiver': receiver, 'message': message}]
    return render(request, 'rooms/private_chats.html', {'chats': chats, 'dpfp': default_pfp})


@login_required
def get_private_chat(request, username):
    sender = request.user
    receiver = get_object_or_404(User, username=username)
    first, second = sorted([sender.username, receiver.username])
    slug = first + second
    room = Room.objects.filter(slug=slug).first()
    if not room:
        name = first.capitalize() + second.capitalize()
        room = Room.objects.create(name=name, slug=slug, private_chat=True)
    messages = room.messages.all()[0:NUMBER_OF_MESSAGES:-1]
    if messages:
        split_dates(messages)
    return render(request, 'rooms/room.html', {'room': room, 'username': username, 'messages': messages, 'dpfp': default_pfp, 'protocol': PROTOCOL})

templates/rooms/private_chats.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %}Chats | {% endblock %}

{% block content %}
<div class=" lg:pt-14 md:pt-9 pt-5 lg:pb-11 md:pb-7 pb-4 text-center">
    <h1 class="lg:text-5xl md:text-3xl text-2xl text-teal-800 dark:text-gray-200">Private Chats</h1>
</div>

<div class="flex justify-center">
    {% if chats %}
        <div class="lg:w-2/4 md:w-8/12 w-full mx-5 md:text-base text-sm">
            {% for chat in chats %}
                <div class="flex overflow-x-hidden px-1 md:px-2 py-1.5 md:py-2 mb-2 bg-cyan-600  dark:bg-cyan-700 text-white dark:text-gray-100 rounded-xl cursor-pointer"  onclick="location.href='{% url "chats:private_chat" chat.receiver.username  %}'">
                    <div class="mx-1 md:h-20 h-14" style="aspect-ratio: 1/1;">
                        <img src="{% if chat.receiver.userprofile.profile_pic %}{{chat.receiver.userprofile.profile_pic.url}}{% else %}{% get_static_prefix %}{{dpfp}}{% endif %}"
                            alt="profile_pic" class="md:rounded-3xl rounded-2xl " style="aspect-ratio: 1/1; object-fit: cover"/>
                    </div>
                    <div class="px-2 py-1 mt-1 mr-5 lg:mr-20">
                        <div class="font-bold"><p>{{ chat.receiver.username }}</p></div>
                        <div>
                            <span class="font-bold">{% if request.user.username == chat.message.user.username %}Me: {% endif %}</span>
                            <span>{{ chat.message.content|truncatechars:80 }}</span>
                        </div>
                    </div> 
                    <div class="flex flex-grow"><div class="mt-auto ml-auto"><p class="mr-1.5 md:mr-3 mb-1 md:mb-2 text-xs">{{ chat.message.date_added|date:'H:i' }}</p></div></div>
                </div>
            {% endfor %}
        </div>
    {% else %}
            <p class="lg:text-2xl md:text-xl text-base text-center text-teal-800 dark:text-gray-200">No Private Chats yet</p>
    {% endif %}
</div>
{% endblock %}

templates/rooms/room.html
{% extends 'main/base.html' %}

{% load static %}

{% block style %}
<style>

    #chat {
        height: 68vh;
    }
    
    @media (min-width: 768px) {
    #chat {
        height: 62vh;
    }

    @media (min-width: 1024px) {
    #chat {
        height: 50vh;
    }
} 
</style>
{% endblock %}

{% block title %}{{ room.name }} | {% endblock %}

{% block content %}
<div class="lg:pt-14 md:pt-9 pt-5 lg:pb-11 md:pb-7 pb-4 text-center">
    <h1 class="text-3xl lg:text-5xl text-teal-800 dark:text-gray-200">{{ username|default:room.name }}</h1>
</div>

<div class="flex flex-col items-center">
    <div class="lg:w-3/4 w-full px-5">
        <div id="chat" class="w-full md:text-base text-sm lg:p-4 md:p-3 p-2 bg-white dark:bg-zinc-900 rounded-xl">
            {% if messages %}
                <div class="chat-messages max-h-full overflow-y-auto space-y-3" id="chat-messages">
                    {% for m in messages %}
                        {% if m.split %}
                            <div class="lg:pt-2 md:pt-1.5 pt-1">
                                <p class="text-center text-gray-400 dark:text-zinc-400">{{ m.split }}</p>
                            </div>
                        {% endif %}
                        
                        {% if request.user.username == m.user.username %}
                            <div class="flex justify-end">
                                <div class="mt-1 ml-5 md:px-2.5 px-2 py-1 rounded-xl bg-amber-400 dark:bg-amber-700 text-white dark:text-gray-100">
                                    <div><p>{{ m.content }}</p></div>
                                    <div class="float-right"><p class="text-xs">{{ m.date_added|date:'H:i' }}</p></div>
                                </div>
                            </div>
                        {% else %}
                            <div class="flex">
                                <div class="lg:h-20 md:h-16 h-10 cursor-pointer" style="aspect-ratio: 1/1;" onclick="location.href='{% url "authentication:profile" m.user.username %}';">
                                    <img src="{% if m.user.userprofile.profile_pic %}{{m.user.userprofile.profile_pic.url}}{% else %}{% get_static_prefix %}{{dpfp}}{% endif %}"
                                        alt="profile_pic" class="w-full md:rounded-3xl rounded-2xl" style="aspect-ratio: 1/1; object-fit: cover"/>
                                </div>
                                <div class="mt-1 mx-1 mr-5 md:px-2.5 px-2 py-1 rounded-xl bg-amber-500 dark:bg-amber-600 text-white dark:text-gray-50">
                                    <div class="md:pb-1 pb-0.5 font-bold"><p>{{ m.user.username }}</p></div>
                                    <div><p>{{ m.content }}</p></div>
                                    <div class="float-right"><p class="text-xs">{{ m.date_added|date:'H:i' }}</p></div>
                                </div> 
                            </div>                  
                        {% endif %}
                    {% endfor %}
                    <template id="mymessage">
                        <div class="flex justify-end">
                            <div class="mt-1 ml-5 md:px-2.5 px-2 py-1 rounded-xl bg-amber-400 dark:bg-amber-700 text-white dark:text-gray-100">
                                <div><p class="mycontent"></p></div>
                                <div class="float-right"><p class="mytime text-xs"></p></div>
                            </div>
                        </div>
                    </template>
                    <template id="message">
                        <div class="flex">
                            <div class="pfpdiv lg:h-20 md:h-16 h-10 cursor-pointer" style="aspect-ratio: 1/1;">
                                <img src="{% get_static_prefix %}{{dpfp}}" alt="profile_pic" class="pfp w-full md:rounded-3xl rounded-2xl" style="aspect-ratio: 1/1;
                                object-fit: cover"/>
                            </div>
                            <div class="mt-1 mx-1 mr-5 md:px-2.5 px-2 py-1 rounded-xl bg-amber-500 dark:bg-amber-600 text-white dark:text-gray-50">
                                <div class="md:pb-1 pb-0.5 font-bold"><p class="username"></p></div>
                                <div><p class="content"></p></div>
                                <div class="float-right"><p class="time text-xs"></p></div>
                            </div>
                        </div>
                    </template>
                </div>
            {% else %}
                <div class="flex h-full items-center justify-center">
                    <p class="lg:text-2xl md:text-xl text-base text-gray-300 dark:text-zinc-500">No messages yet</p>
                </div>
            {% endif %}
        </div>

        <div class="w-full md:mt-4 mt-3 lg:mx-auto lg:p-4 md:p-3 p-2 bg-white dark:bg-zinc-900 rounded-xl">
            <form method="post" action="." class="flex">
                {% csrf_token %}
                <textarea type="text" name="content" autofocus="true" class="flex-grow px-1 lg:mr-3 md:mr-2.5 mr-1.5 rounded-lg outline-none dark:bg-zinc-900 dark:text-gray-100 placeholder:text-gray-400 dark:placeholder:text-zinc-400" placeholder="Your message..." rows="1" id="chat-message-input"></textarea>
                <button class="md:px-5 px-4 md:py-3 py-2.5 rounded-xl font-medium text-white dark:text-gray-100 bg-teal-500 hover:bg-teal-600 
                dark:bg-teal-600 dark:hover:bg-teal-500" id="chat-message-submit">
                    Submit
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{{ protocol|json_script:"json-protocol" }}
{{ room.slug|json_script:"json-roomname" }}
{{ request.user.username|json_script:"json-username" }}
{% if request.user.userprofile.profile_pic %}
    {{ request.user.userprofile.profile_pic.url|json_script:"json-pfp" }}
{% else %}
    {{ ''|json_script:"json-pfp" }}
{% endif %}
{% url "authentication:profile" 'user' as profile_url %}
{{ profile_url|json_script:"json-url" }}

<script>
    const protocol = JSON.parse(document.getElementById('json-protocol').textContent);
    const roomName = JSON.parse(document.getElementById('json-roomname').textContent);
    const userName = JSON.parse(document.getElementById('json-username').textContent);
    const userPfp = JSON.parse(document.getElementById('json-pfp').textContent);
    const pfUrl = JSON.parse(document.getElementById('json-url').textContent);
    const chatSocket = new WebSocket(
        protocol
        + '://'
        + window.location.host
        + '/ws/'
        + roomName
        + '/'
    );

    const messages = document.querySelector('#chat-messages');
    const input = document.querySelector('#chat-message-input');
    const submitBtn = document.querySelector('#chat-message-submit');

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);

        let clone;
        if (data.username === userName) {
            const template = document.querySelector('#mymessage');
            clone = template.content.cloneNode(true);
            const mtext = clone.querySelector(".mycontent");
            mtext.textContent = data.message;
            const mtime = clone.querySelector(".mytime");
            mtime.textContent = data.time;
        } else {
            const template = document.querySelector('#message');
            clone = template.content.cloneNode(true);
            const musername = clone.querySelector(".username");
            musername.textContent = data.username;
            const mtext = clone.querySelector(".content");
            mtext.textContent = data.message;
            const mpfp = clone.querySelector(".pfp");
            if (data.pfp !== '') {
                mpfp.src = data.pfp;
            }
            const pfpl = clone.querySelector(".pfpdiv");
            const url = pfUrl.replace("user", data.username);
            pfpl.setAttribute('onclick', `location.href="${url}"`);
            const mtime = clone.querySelector(".time");
            mtime.textContent = data.time;
        }
        messages.appendChild(clone);       

        scrollToBottom();
    };

    chatSocket.onclose = function(e) {
        alert("Oops, connection problem. Please refresh the page and try again");
    }

    input.onkeydown = function(e) {
        if (e.key == "Enter" && !e.shiftKey) {
            submitBtn.click();
        }
    };    

    submitBtn.addEventListener("click", function(e) {
        e.preventDefault();

        const messageInput = document.querySelector('#chat-message-input');
        const message = messageInput.value;
        
        if (message) {
            chatSocket.send(JSON.stringify({
                'message': message,
                'pfp': userPfp,
            }));
        }

        document.querySelector('form').reset();
        
        return false;
    });


    // Function for finding the messages element, and scrolling to the bottom of it.
    function scrollToBottom() {
        messages.scrollTop = messages.scrollHeight;
    }

    // To trigger the scroll on load.
    scrollToBottom();

</script>
{% endblock %}

templates/rooms/rooms.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %}Rooms | {% endblock %}

{% block content %}
<div class="lg:pt-14 md:pt-9 pt-5 lg:pb-10 md:pb-5 pb-2.5 text-center">
    <h1 class="lg:text-5xl md:text-3xl text-2xl text-teal-800 dark:text-gray-200">Rooms</h1>
</div>

<div class="w-full flex flex-wrap justify-center">
    {% for chat in chats %}
        <div class="min-w-fit w-full md:w-2/3 lg:w-1/4 p-2 md:p-3 mx-5 my-1.5 bg-teal-blue dark:bg-dteal-blue text-white dark:text-gray-100 rounded-xl cursor-pointer" onclick="location.href='{% url "chats:room" chat.room.slug %}'">
            <div class="text-center">
                <h2 class="mb-1 md:mb-2 text-base md:text-2xl font-semibold">{{ chat.room.name }}</h2>
            </div>
            {% if chat.message %}
                <div class="min-w-fit flex p-2 bg-dteal-blue dark:bg-teal-blue rounded-xl">
                    <div class="mr-1 md:h-20 h-12" style="aspect-ratio: 1/1;">
                        <img src="{% if chat.message.user.userprofile.profile_pic %}{{chat.message.user.userprofile.profile_pic.url}}{% else %}{% get_static_prefix %}{{dpfp}}{% endif %}"
                            alt="profile_pic" class="md:rounded-3xl rounded-2xl" style="aspect-ratio: 1/1; object-fit: cover"/>
                    </div>
                    <div class="text-xs md:text-base px-1 md:px-2 md:py-1 mt-1 mr-1 rounded-xl">
                        <div class="font-bold"><p>{{ chat.message.user.username }}</p></div>
                        <div><p>{{ chat.message.content|truncatechars:25 }}</p></div>
                    </div>
                    <div class="hidden md:flex flex-grow"><div class="float-right mt-auto ml-auto"><p class="mr-1.5 md:mr-3 mb-1 md:mb-2  text-xs">{{ chat.message.date_added|date:'H:i' }}</p></div></div>
                </div>
            {% endif %}  
        </div>
    {% endfor %}
</div>
{% endblock %}