authentication/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "authentication"

urlpatterns = [
    path('signup/', views.SignUpFormView.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='authentication/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.update_profile, name='update_profile'),
    path('profile/<str:username>/', views.ProfileDetailView.as_view(), name='profile'),
]

chatproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('main.urls')),
    path('', include('authentication.urls')),
    path('chats/', include('rooms.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    path('', views.get_frontpage, name='frontpage'),
]

rooms/urls.py
from django.urls import path

from . import views

app_name = "chats"

urlpatterns = [
    path('private/', views.list_private_chats, name='private_chats'),
    path('private/<str:username>/', views.get_private_chat, name='private_chat'),
    path('<slug:slug>/', views.get_room, name='room'),
    path('', views.list_rooms, name='rooms'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.urls import reverse

from rooms.models import Message

default_pfp = 'images/default_avatar.jpg'

NUMBER_OF_MESSAGES = 5


# Create your views here.
def get_frontpage(request):
    if request.user.is_authenticated:
        messages = Message.objects.filter(user=request.user)[0:NUMBER_OF_MESSAGES:-1]
        rooms = set([message.room for message in messages])
        if not rooms:
            return redirect(reverse('chats:rooms'))
        chats = []
        for room in rooms:
            message = room.messages.all().first()
            if room.private_chat:
                username = room.slug.replace(request.user.username, '')
                receiver = User.objects.get(username=username)
                chats += [{'private': True, 'receiver': receiver, 'message': message}]
            else:
                chats += [{'private': False, 'room': room, 'message': message}]
        return render(request, 'main/frontpage.html', {'chats': chats, "dpfp": default_pfp})
    else:
        return render(request, 'main/frontpage.html')

templates/main/base.html
{% load static %}

<!DOCTYPE html>

<html>
    {% load tailwind_tags %}
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{% block title %}{% endblock %}Chat</title>
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">

        {% tailwind_css %}

        <script>
            // It's best to inline this in `head` to avoid FOUC (flash of unstyled content) when changing pages or themes
            if (
              localStorage.getItem('color-theme') === 'dark' ||
              (!('color-theme' in localStorage) &&
                window.matchMedia('(prefers-color-scheme: dark)').matches)
            ) {
              document.documentElement.classList.add('dark');
            } else {
              document.documentElement.classList.remove('dark');
            }
          </script>

        <style>          
            .messages {
                height: 400px;
                overflow-y: auto;
            }

            .switch-ball {
                background-image: url({% static 'images/sun.png' %});
                background-position: center;
                background-repeat: no-repeat;
                background-size: cover;
                background-origin: content-box;
                transition: transform 0.3s linear;
            }

            #checkbox:checked + label .switch-ball {
                background-image: url({% static 'images/moon.png' %});
            }

            @media (min-width: 1024px) {
                #checkbox:checked + label .switch-ball {
                    transform: translateX(50px);
                }
            }
        </style>
        {% block style %}
        {% endblock %}
    </head>

    <body class="bg-light-cyan dark:bg-teal-900">
        <nav class="flex items-center justify-between lg:px-5 md:px-4 px-3 lg:py-5 md:py-4 py-3 bg-tiffany-blue dark:bg-teal-700">
            <div>
                <a href="/" class="lg:text-2xl md:text-xl text-base text-white dark:text-gray-100 font-bold">Chat</a>
            </div>
            <div class="flex items-center lg:space-x-4 md:space-x-3 space-x-2 text-sm md:text-base">
                {% if request.user.is_authenticated %}
                    <!-- <a href="{% url 'chats:rooms' %}" class="hidden md:inline font-semibold text-white hover:text-gray-200">Rooms</a> -->
                    <a href="{% url 'chats:rooms' %}" class="font-semibold text-white dark:text-gray-100 hover:text-gray-200 dark:hover:text-white"><img src="{% static 'images/rooms.png' %}" alt="" class="inline md:hidden dark:hidden w-6"><img src="{% static 'images/rooms_dark.png' %}" alt="" class="hidden dark:inline md:dark:hidden w-6"><span class="hidden md:inline">Rooms</span></a>
                    <a href="{% url 'chats:private_chats' %}" class="font-semibold text-white dark:text-gray-100 hover:text-gray-200 dark:hover:text-white"><img src="{% static 'images/chats.png' %}" alt="" class="inline md:hidden dark:hidden w-6 ml-1.5 mr-2"><img src="{% static 'images/chats_dark.png' %}" alt="" class="hidden dark:inline md:dark:hidden w-6 ml-1.5 mr-2"><span class="hidden md:inline">Private Chats</span></a>
                    <a href="{% url 'authentication:logout' %}" class="lg:px-5 px-2 lg:py-3 py-1 rounded-xl font-semibold text-white dark:text-gray-100 bg-teal-600 hover:bg-teal-700 dark:bg-teal-600  
                    dark:hover:bg-teal-500">Log Out</a>
                {% else %}
                    <a href="{% url 'authentication:login' %}" class="font-semibold text-white dark:text-gray-100 hover:text-gray-200 dark:hover:text-white">Log In</a>
                    <a href="{% url 'authentication:signup' %}" class="lg:px-5 px-2 lg:py-3 py-1 rounded-xl font-semibold text-white dark:text-gray-100 bg-teal-600 hover:bg-teal-700 dark:bg-teal-600  
                    dark:hover:bg-teal-500">Sign Up</a>
                {% endif %}

                <div>
                    <input type="checkbox" name="" id="checkbox" class="hidden" />
                    <label for="checkbox" class="cursor-pointer">
                      <div class="lg:w-20 w-6 lg:h-10 h-6 flex items-center bg-gray-200 dark:bg-neutral-700 rounded-full lg:px-1">
                        <div class="switch-ball lg:w-8 w-6 lg:h-8 h-6 p-1 bg-gray-50 dark:bg-gray-200 rounded-full shadow"></div>
                      </div>
                    </label>
                </div>
                {% if request.user.is_authenticated %}
                <div class="lg:h-10 h-6 mx-1 cursor-pointer" style="aspect-ratio: 1/1;" onclick="location.href='{% url "authentication:update_profile" %}';">
                    <img src="{% if request.user.userprofile.profile_pic %}{{request.user.userprofile.profile_pic.url}}{% else %}{% static 'images/default_avatar.jpg' %}{% endif %}"
                        alt="profile_pic" class="rounded-2xl md:rounded-3xl" style="aspect-ratio: 1/1; object-fit: cover"/>
                </div>
                {% endif %}
            </div>
        </nav>

        {% block content %}
        {% endblock %}

        <script>
            const checkbox = document.querySelector("#checkbox");
            const html = document.querySelector("html");

            const toggleDarkMode = function () {
                if (checkbox.checked) {
                    html.classList.add("dark");
                    localStorage.setItem('color-theme', 'dark');
                } else {
                    html.classList.remove("dark");
                    localStorage.setItem('color-theme', 'light');
                }
            }
            if (html.classList.contains('dark')) {
                checkbox.checked = true
            }
            checkbox.addEventListener("click", toggleDarkMode);
        </script>

        {% block scripts %}
        {% endblock %}
    </body>
</html>

templates/main/frontpage.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %}Welcome | {% endblock %}

{% block content %}
<div class="mb-0 lg:pt-20 md:pt-14 pt-6 lg:pb-7 md:pb-4 pb-1.5 text-center">
    <h1 class="lg:text-6xl md:text-4xl text-2xl text-teal-800 dark:text-gray-200">Real-Time Chat App</h1>
</div>
{% if request.user.is_authenticated %}
    <div>
        <div class="lg:pb-5 md:pb-3.5 pb-2 text-center">
            <h2 class="lg:text-4xl md:text-2xl text-lg text-teal-800 dark:text-gray-200">Latest messages</h2>
        </div>
        <div class="lg:w-2/4 lg:mx-auto md:mx-7 mx-3 text-sm md:text-base">
            {% for chat in chats %}
                {% if chat.private %}
                    <div class="flex overflow-x-hidden mb-2 md:mb-3 px-1 md:px-2 py-1.5 md:py-2 bg-cyan-600  dark:bg-cyan-700 text-white dark:text-gray-100 rounded-xl cursor-pointer"  onclick="location.href='{% url "chats:private_chat" chat.receiver.username  %}'">
                        <div class="mx-1 h-16 md:h-20" style="aspect-ratio: 1/1;">
                            <img src="{% if chat.receiver.userprofile.profile_pic %}{{chat.receiver.userprofile.profile_pic.url}}{% else %}{% get_static_prefix %}{{dpfp}}{% endif %}"
                                alt="profile_pic" class="md:rounded-3xl rounded-2xl" style="aspect-ratio: 1/1; object-fit: cover"/>
                        </div>
                        <div class="mt-1 mr-5 lg:mr-20 px-2 py-1">
                            <div class="font-bold"><p>{{ chat.receiver.username }}</p></div>
                            <div>
                                <span class="font-bold">{% if request.user.username == chat.message.user.username %}Me: {% endif %}</span>
                                <span>{{ chat.message.content|truncatechars:80 }}</span>
                            </div>
                        </div>
                        <div class="flex flex-grow"><div class="float-right mt-auto ml-auto"><p class="mr-1.5 md:mr-3 mb-1 md:mb-2 text-xs">{{ chat.message.date_added|date:'H:i' }}</p></div></div>
                    </div>
                {% else %}
                    <div class="flex overflow-x-hidden mb-2 md:mb-3 px-1 md:px-2 py-1.5 md:py-2 bg-teal-blue dark:bg-dteal-blue text-white dark:text-gray-100 rounded-xl cursor-pointer"  onclick="location.href='{% url "chats:room" chat.room.slug  %}'">
                        <div class="mx-1 h-16 md:h-20" style="aspect-ratio: 1/1;">
                            <img src="{% if chat.message.user.userprofile.profile_pic %}{{chat.message.user.userprofile.profile_pic.url}}{% else %}{% get_static_prefix %}{{dpfp}}{% endif %}"
                                alt="profile_pic" class="md:rounded-3xl rounded-2xl" style="aspect-ratio: 1/1; object-fit: cover"/>
                        </div>
                        <div class="mt-1 mr-5 lg:mr-20 px-2 py-1">
                            <div class="font-bold"><p>{{ chat.room.name }}</p></div>
                            <div>
                                <span>{{ chat.message.content|truncatechars:80 }}</span>
                            </div>
                        </div>
                        <div class="flex flex-grow"><div class="float-right mt-auto ml-auto"><p class="mr-1.5 md:mr-3 mb-1 md:mb-2 text-xs">{{ chat.message.date_added|date:'H:i' }}</p></div></div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% else %}
    <div class="mx-2 text-center text-teal-800 dark:text-gray-200">
        <p class="lg:text-3xl md:text-2xl text-base lg:pt-1.5 md:pt-1 pt-0.5 lg:pb-6 md:pb-3 pb-2 leading-snug">Log In or Sign Up to message in Rooms or start a Private Chat</p>
        <p class="lg:text-xl md:text-lg text-sm font-medium mx-6 md:pb-1 pb-1.5"><a href="https://github.com/uliana-dzyoba">Check out my other projects on <span class="underline">GitHub</span></a></p>
        <p class="lg:text-lg md:text-base text-xs font-medium"><a href="mailto:ulianadzyoba@gmail.com">Contact me at: <span class="underline">ulianadzyoba@gmail.com</span></a></p>
    </div>
{% endif %}
{% endblock %}